sudo: required
dist: trusty
language: php
php:
  - 7
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
before_install:
  - composer self-update
install:
  - composer update --ignore-platform-reqs --prefer-source
before_script:
  - phpenv config-add travis-php.ini
script:
  - phpunit --coverage-clover=coverage.clover
after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
cache:
  directories:
    - $HOME/.composer/cache
